### ISSUE TITLE
Parser uses undefined method `@error`

### ISSUE THREAD

**Issue by clayallsopp** [jsdf/coffee-react-transform#42]
From [parser.coffee](https://github.com/jsdf/coffee-react-transform/blob/de7e41bc74c6286c07a1524243bb72c408c18881/src/parser.coffee#L355):

```coffee
@error "missing #{ stack.pop() }, starting"
```

I can't find a reference to `this.error` anywhere else in the codebase - is this intentional? the blame dates back to may 2014, and I can't find references around there either

**Comment by jsdf** [comment]
Yep the parser was 'originally' a fork of the Coffeescript lexer, looks like is missed it when adapting that code. Cheers

**Comment by jsdf** [comment]
Fixed by https://github.com/jsdf/coffee-react-transform/commit/a920502f91bbe360882626e49835b172b2a36b88

**Comment by clayallsopp** [comment]
Thanks!
