### ISSUE TITLE
The CJSX Name

### ISSUE THREAD

**Issue by daniellmb** [jsdf/coffee-react-transform#43]
If JSX means JavaScript XML then it seems to me that the name for Coffee React should be CSX for CoffeeScript XML not CJSX that stands for CoffeeScript JavaScript XML.

**Comment by jsdf** [comment]
http://stackoverflow.com/questions/25405941/what-are-csx-c-sharp-files-for

**Comment by daniellmb** [comment]
well... that sux... who uses that?! ;)
