### ISSUE TITLE
Ommit closing tags.

### ISSUE THREAD

**Issue by fazibear** [jsdf/coffee-react-transform#58]
Is there an option to ommit closing tags and use indentation for this ?

```
render ->
  <div>
    <h1>
      Header
    </h1>
  </div>
```

```
render ->
  <div>
    <h1>
      Header
```

**Comment by roryokane** [comment]
If you use plain CoffeeScript with no transform, you don’t have to type a closing tag that repeats the tag name. You still have to devote a line to a closing `]` though.

```coffee
e = React.createElement.bind(React)

render: ->
  e "div", {}, [
    e "h1", {}, [
      "Header"
    ]
  ]
```

A conversion of the [README’s example](https://github.com/jsdf/coffee-react-transform#example) to plain CoffeeScript:

```coffee
e = React.createElement.bind(React)

Car = React.createClass
  render: ->
    e Vehicle, {doors: 4, locked: isLocked(), "data-colour": "red", on: true}, [
      e Parts.FrontSeat
      e Parts.BackSeat
      e "p", {className: "seat"}, ["Which seat can I take? ", @props?.seat or 'none']
      # also, this is a comment
    ]
```

For easy comparison, here is the example in the README:

> ```coffee
> Car = React.createClass
>   render: ->
>     <Vehicle doors={4} locked={isLocked()} data-colour="red" on>
>       <Parts.FrontSeat />
>       <Parts.BackSeat />
>       <p className="seat">Which seat can I take? {@props?.seat or 'none'}</p>
>       {# also, this is a comment }
>     </Vehicle>
> ```

**Comment by jsdf** [comment]
This would require substantial work, and I'd consider this a marginal use case (maybe check out Teact instead).
