### ISSUE TITLE
React v15 removed React.__spread

### ISSUE THREAD

**Issue by nil4** [jsdf/coffee-react-transform#70]
[React v15](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) removed `React.__spread` and this change breaks everyone using `csx-loader` (see https://github.com/KyleAMathews/react-spinkit/issues/28 for an example). It seems it will be [added back temporarily](https://github.com/facebook/react/pull/6444) but given the deprecation warning, it does not look like a good long-term solution.

**Comment by jsdf** [comment]
Thanks for letting me know. I think supporting __spread and Object.assign via a config option is probably the way to go

**Comment by nil4** [comment]
FYI https://github.com/Microsoft/TypeScript/issues/7270#issuecomment-207136958: 

> We’ll temporarily bring it back [...]. However the method is deprecated and will go away in the next major release.

**Comment by abejfehr** [comment]
It looks like 4a4077a fixes this...can the updated version of this package be published to npm?

**Comment by jsdf** [comment]
Fixed in [v4.0.0](https://github.com/jsdf/coffee-react-transform/tree/v4.0.0)
